### ISSUE TITLE
Support Redis Sentinel (and other options)

### ISSUE THREAD

**Issue by tam5** [simplesamlphp/simplesamlphp#1137]
**Describe the solution you'd like**
As of [Predis v1.1.0](https://github.com/nrk/predis/releases/tag/v1.1.0), `redis-sentinel` is supported. https://redis.io/topics/sentinel

This requires passing some additional options to the `Predis\Client` constructor. It seems here
[SimpleSAML/Store/Redis.php](https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/Store/Redis.php#L33-L47) that there is no way to pass additional configuration to Redis, rather each key is hardcoded.

It would be great to allow passthrough of additional options to the client, this way the sentinel feature, as well as others, could be supported. If not, then at least the `replication` and `service` parameters should be supported.

**Comment by tvdijen** [comment]
It would help if you can run some tests with the patch I wrote in #701

**Comment by tvdijen** [comment]
Any chance you can help us out with some testing @tam5 ?

**Comment by tam5** [comment]
@tvdijen yes, just have not had time yet

**Comment by tvdijen** [comment]
@lonoak or @tam5 It would be very helpful if either of you test the patch I wrote so we can finally close this Issue

**Comment by tam5** [comment]
Hey @tvdijen , really sorry about that. Anyway, I've started to test it, so far I have a few errors to report, probably due to this PR getting a bit stale:


```
PHP Fatal error:  Uncaught Error: Cannot use object of type Predis\\Response\\Error as array in /opt/app/simplesamlphp/vendor/predis/predis/src/Connection/Aggregate/SentinelReplication.php:526\nStack trace:\n#0 /opt/app/simplesamlphp/vendor/predis/predis/src/Connection/Aggregate/SentinelReplication.php(542): Predis\\Connection\\Aggregate\\SentinelReplication->assertConnectionRole(Object(Predis\\Connection\\StreamConnection), 'master')\n#1 /opt/app/simplesamlphp/vendor/predis/predis/src/Connection/Aggregate/SentinelReplication.php(658): Predis\\Connection\\Aggregate\\SentinelReplication->getConnection(Object(Predis\\Command\\StringSetExpire))\n#2 /opt/app/simplesamlphp/vendor/predis/predis/src/Connection/Aggregate/SentinelReplication.php(698): Predis\\Connection\\Aggregate\\SentinelReplication->retryCommandOnFailure(Object(Predis\\Command\\StringSetExpire), 'executeCommand')\n#3 /opt/app/simplesamlphp/vendor/predis/predis/src/Client.php(331): Predis\\Connection\\Aggregate\\SentinelReplication->executeCommand(Object(Predis\\Command\\StringSetExpire))\n#4 / in /opt/app/simplesamlphp/vendor/predis/predis/src/Connection/Aggregate/SentinelReplication.php on line 526
lisso_1           | [Thu Jun 11 17:25:11.801020 2020] [php7:notice] [pid 8] [client 172.18.0.1:40442] PHP Stack trace:
lisso_1           | [Thu Jun 11 17:25:11.801037 2020] [php7:notice] [pid 8] [client 172.18.0.1:40442] PHP   1. {main}() /opt/app/simplesamlphp/www/module.php:0
lisso_1           | [Thu Jun 11 17:25:11.801049 2020] [php7:notice] [pid 8] [client 172.18.0.1:40442] PHP   2. SimpleSAML\\Module::process() /opt/app/simplesamlphp/www/module.php:9
lisso_1           | [Thu Jun 11 17:25:11.801066 2020] [php7:notice] [pid 8] [client 172.18.0.1:40442] PHP   3. require() /opt/app/simplesamlphp/lib/SimpleSAML/Module.php:236
lisso_1           | [Thu Jun 11 17:25:11.801078 2020] [php7:notice] [pid 8] [client 172.18.0.1:40442] PHP   4. SimpleSAML\\Utils\\Auth::requireAdmin() /opt/app/simplesamlphp/modules/core/www/frontpage_welcome.php:9
lisso_1           | [Thu Jun 11 17:25:11.801092 2020] [php7:notice] [pid 8] [client 172.18.0.1:40442] PHP   5. SimpleSAML\\Auth\\Simple->login() /opt/app/simplesamlphp/lib/SimpleSAML/Utils/Auth.php:88
lisso_1           | [Thu Jun 11 17:25:11.801106 2020] [php7:notice] [pid 8] [client 172.18.0.1:40442] PHP   6. SimpleSAML\\Module\\core\\Auth\\Source\\AdminPassword->initLogin() /opt/app/simplesamlphp/lib/SimpleSAML/Auth/Simple.php:165
lisso_1           | [Thu Jun 11 17:25:11.801119 2020] [php7:notice] [pid 8] [client 172.18.0.1:40442] PHP   7. SimpleSAML\\Module\\core\\Auth\\Source\\AdminPassword->authenticate() /opt/app/simplesamlphp/lib/SimpleSAML/Auth/Source.php:193
lisso_1           | [Thu Jun 11 17:25:11.801134 2020] [php7:notice] [pid 8] [client 172.18.0.1:40442] PHP   8. SimpleSAML\\Utils\\HTTP::redirectTrustedURL() /opt/app/simplesamlphp/modules/core/lib/Auth/UserPassBase.php:221
lisso_1           | [Thu Jun 11 17:25:11.801144 2020] [php7:notice] [pid 8] [client 172.18.0.1:40442] PHP   9. SimpleSAML\\Utils\\HTTP::redirect() /opt/app/simplesamlphp/lib/SimpleSAML/Utils/HTTP.php:970
```


Also a bunch of warnings due to namespace change, for example:

```
 The class or interface 'sspmod_core_Auth_Source_AdminPassword' is now using namespaces, please use 'SimpleSAML\\Module\\core\\Auth\\Source\\AdminPassword' instead.
```

**Comment by tvdijen** [comment]
Well, then let's see what happens if we rebase it! I will do that and then we'll see what happens

**Comment by tvdijen** [comment]
It's this one and it has been rebased:
https://github.com/tvdijen/simplesamlphp/tree/redissentinel

**Comment by tam5** [comment]
ill try that one now

**Comment by tam5** [comment]
Hmm ok, this https://github.com/tvdijen/simplesamlphp/tree/redissentinel looks a bit better. However, I still have this error:

```
 PHP Fatal error:  Uncaught Error: Cannot use object of type Predis\\Response\\Error as array in /opt/app/simplesamlphp/vendor/predis/predis/src/Connection/Aggregate/SentinelReplication.php:526\nStack trace:\n#0 /opt/app/simplesamlphp/vendor/predis/predis/src/Connection/Aggregate/SentinelReplication.php(542): Predis\\Connection\\Aggregate\\SentinelReplication->assertConnectionRole(Object(Predis\\Connection\\StreamConnection), 'slave')\n#1 /opt/app/simplesamlphp/vendor/predis/predis/src/Connection/Aggregate/SentinelReplication.php(658): Predis\\Connection\\Aggregate\\SentinelReplication->getConnection(Object(Predis\\Command\\StringGet))\n#2 /opt/app/simplesamlphp/vendor/predis/predis/src/Connection/Aggregate/SentinelReplication.php(698): Predis\\Connection\\Aggregate\\SentinelReplication->retryCommandOnFailure(Object(Predis\\Command\\StringGet), 'executeCommand')\n#3 /opt/app/simplesamlphp/vendor/predis/predis/src/Client.php(331): Predis\\Connection\\Aggregate\\SentinelReplication->executeCommand(Object(Predis\\Command\\StringGet))\n#4 /opt/app/simplesamlp in /opt/app/simplesamlphp/vendor/predis/predis/src/Connection/Aggregate/SentinelReplication.php on line 526
```

Looks like Predis is getting an error, which might be my fault, but I don't have a proper error message since looks like we error when trying to catch the error.

**Comment by tvdijen** [comment]
Hmm, I don't see any way to enable debug logging in the library either..
