### ISSUE TITLE
Uncaught exception 'SimpleSAML\Error\Exception' with message 'No private key found in metadata.' in /var/www/vhosts/traneleads.com/httpdocs/auth/lib/SimpleSAML/Utils/Crypto.php:208

### ISSUE THREAD

**Issue by burhan-njom** [simplesamlphp/simplesamlphp#1590]
Fatal error: Uncaught exception 'SimpleSAML\Error\Exception' with message 'No private key found in metadata.' in /var/www/vhosts/example.com/httpdocs/auth/lib/SimpleSAML/Utils/Crypto.php:208 Stack trace: #0 /var/www/vhosts/example.com/httpdocs/auth/modules/saml/lib/Message.php(52): SimpleSAML\Utils\Crypto::loadPrivateKey(Object(SimpleSAML\Configuration), true) #1 /var/www/vhosts/example.com/httpdocs/auth/modules/saml/lib/Message.php(120): SimpleSAML\Module\saml\Message::addSign(Object(SimpleSAML\Configuration), Object(SimpleSAML\Configuration), Object(SAML2\AuthnRequest)) #2 /var/www/vhosts/example.com/httpdocs/auth/modules/saml/lib/Message.php(544): SimpleSAML\Module\saml\Message::addRedirectSign(Object(SimpleSAML\Configuration), Object(SimpleSAML\Configuration), Object(SAML2\AuthnRequest)) #3 /var/www/vhosts/example.com/httpdocs/auth/modules/saml/lib/Auth/Source/SP.php(512): SimpleSAML\Module\saml\Message::buildAuthnRequest(Object(SimpleSAML\Configuration), Object(SimpleSAML\Configuration)) #4 /var/www/vh in /var/www/vhosts/example.com/httpdocs/auth/lib/SimpleSAML/Utils/Crypto.php on line 208

What am I missing? Doesn't the idp meta provide the required key info?

**Comment by burhan-njom** [comment]
Can you please delete this issue?
