### ISSUE TITLE
2.0.0-rc2: PHP Fatal error:  Uncaught Error: Typed property SimpleSAML\\Session::$trackid must not be accessed before initialization

### ISSUE THREAD

**Issue by jsokol** [simplesamlphp/simplesamlphp#1724]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Describe the bug**
I've been working on converting our older 1.19.5 implementation over to the 2.0.0-rc2 in anticipation that this will become the new stable version shortly.  I have an application that uses SimpleSAMLphp as a service provider and communicates with a remote IdP. I was testing my application pre-upgrade and it worked fine.  However, when I update to my 2.0.0-rc2 code, I receive the following PHP fatal error:

`[Sun Dec 11 22:54:20.785519 2022] [php:error] [pid 2963072] [client 70.114.146.81:56680] PHP Fatal error:  Uncaught Error: Typed property SimpleSAML\\Session::$trackid must not be accessed before initialization in /var/www/dev.simplerisk.com/www/simplerisk/vendor/simplesamlphp/simplesamlphp/src/SimpleSAML/Session.php:555\nStack trace:\n#0 /var/www/dev.simplerisk.com/www/simplerisk/vendor/simplesamlphp/simplesamlphp/src/SimpleSAML/Session.php(402): SimpleSAML\\Session->getTrackID()\n#1 /var/www/dev.simplerisk.com/www/simplerisk/vendor/simplesamlphp/simplesamlphp/src/SimpleSAML/Session.php(284): SimpleSAML\\Session::load()\n#2 /var/www/dev.simplerisk.com/www/simplerisk/vendor/simplesamlphp/simplesamlphp/src/SimpleSAML/Auth/Simple.php(52): SimpleSAML\\Session::getSessionFromRequest()\n#3 /var/www/dev.simplerisk.com/www/simplerisk/extras/authentication/login.php(56): SimpleSAML\\Auth\\Simple->__construct()\n#4 {main}\n  thrown in /var/www/dev.simplerisk.com/www/simplerisk/vendor/simplesamlphp/simplesamlphp/src/SimpleSAML/Session.php on line 555, referer: https://dev.simplerisk.com/index.php`

I checked my code and it is using the $as = new \SimpleSAML\Auth\Simple('default-sp'); code as recommended in the documentation.  Is this no longer appropriate for the 2.0.0-rc2 release?  

**To Reproduce**
1. Go to 'https://dev.simplerisk.com'
2. Click on 'Go to SSO Login Page'
3. You will see the 500 error associated with this error message above.

**Expected behavior**
I would have expected it to make the SAML request to authenticate with the IdP.

Thanks for your help!

**Comment by jsokol** [comment]
I opened the site in incognito and am no longer getting this result.  It appears to be something related to that session.  Sorry for the extra noise.

**Comment by tvdijen** [comment]
I was just checking this out and I couldn't reproduce.. Did you perhaps forget to clear your session storage after upgrading?

**Comment by jsokol** [comment]
@tvdijen I don't believe I did clear the session storage after upgrading so that certainly could be part of it.  I'm chasing another issue now where the samltest.id side isn't working.  Seems like something changed withe metadata files that I'm trying to work through, but I think this is more of a me issue to figure out how to fix than a you issue.  If you have thoughts, though, I'm all ears.  Here's the log from the samltest.id side:

```
2022-12-11 23:39:07,303 - DEBUG [org.opensaml.saml.saml2.binding.decoding.impl.HTTPRedirectDeflateDecoder:?] - Decoded SAML message
2022-12-11 23:39:07,303 - DEBUG [PROTOCOL_MESSAGE:?] - 
<?xml version="1.0" encoding="UTF-8"?>
<samlp:AuthnRequest
    AssertionConsumerServiceURL="https://dev.simplerisk.com/vendor/simplesamlphp/simplesamlphp/www/module.php/saml/sp/saml2-acs.php/default-sp"
    Destination="https://samltest.id/idp/profile/SAML2/Redirect/SSO"
    ID="_6eb3528e3c3bf9cd962201d76ff4a0f9a3981aadad"
    IssueInstant="2022-12-11T23:39:06Z"
    ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
    Version="2.0" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
    <saml:Issuer>https://dev.simplerisk.com/vendor/simplesamlphp/simplesamlphp/www/module.php/saml/sp/metadata.php/default-sp</saml:Issuer>
    <samlp:NameIDPolicy AllowCreate="true" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"/>
</samlp:AuthnRequest>

2022-12-11 23:39:07,312 - DEBUG [org.opensaml.saml.metadata.resolver.impl.AbstractBatchMetadataResolver:?] - Metadata Resolver FilesystemMetadataResolver SAMLtest: Resolved 0 candidates via EntityIdCriterion: EntityIdCriterion [id=https://dev.simplerisk.com/vendor/simplesamlphp/simplesamlphp/www/module.php/saml/sp/metadata.php/default-sp]
2022-12-11 23:39:07,312 - DEBUG [org.opensaml.saml.metadata.resolver.impl.PredicateRoleDescriptorResolver:?] - Resolved no EntityDescriptors via underlying MetadataResolver, returning empty collection
2022-12-11 23:39:07,312 - INFO [org.opensaml.saml.common.binding.impl.SAMLMetadataLookupHandler:?] - Message Handler:  No metadata returned for https://dev.simplerisk.com/vendor/simplesamlphp/simplesamlphp/www/module.php/saml/sp/metadata.php/default-sp in role {urn:oasis:names:tc:SAML:2.0:metadata}SPSSODescriptor with protocol urn:oasis:names:tc:SAML:2.0:protocol
2022-12-11 23:39:07,312 - DEBUG [org.opensaml.saml.common.binding.impl.SAMLAddAttributeConsumingServiceHandler:?] - Message Handler:  No metadata context found, nothing to do
2022-12-11 23:39:07,312 - DEBUG [net.shibboleth.idp.saml.profile.impl.InitializeRelyingPartyContextFromSAMLPeer:?] - Profile Action InitializeRelyingPartyContextFromSAMLPeer: Attaching RelyingPartyContext based on SAML peer https://dev.simplerisk.com/vendor/simplesamlphp/simplesamlphp/www/module.php/saml/sp/metadata.php/default-sp
2022-12-11 23:39:07,312 - WARN [net.shibboleth.idp.profile.impl.SelectProfileConfiguration:117] - Profile Action SelectProfileConfiguration: Profile http://shibboleth.net/ns/profiles/saml2/sso/browser is not available for RP configuration shibboleth.UnverifiedRelyingParty (RPID https://dev.simplerisk.com/vendor/simplesamlphp/simplesamlphp/www/module.php/saml/sp/metadata.php/default-sp)
2022-12-11 23:39:07,313 - WARN [org.opensaml.profile.action.impl.LogEvent:105] - A non-proceed event occurred while processing the request: InvalidProfileConfiguration
2022-12-11 23:39:07,313 - DEBUG [org.opensaml.saml.common.profile.logic.DefaultLocalErrorPredicate:?] - No SAMLBindingContext or binding URI available, error must be handled locally
```

**Comment by tvdijen** [comment]
The whole `vendor/simplesamlphp/simplesamlphp/www` part shouldn't be there. Must be some misconfiguration on your end.

**Comment by thijskh** [comment]
It seems your metadata url does not give output (I'm a bit confused by the `vendor/simplesamlphp/simplesamlphp/www/` paths in your URL but that may just be your setup..). Maybe you can check the URL In your browser to see what it does an/or what is logged.

**Comment by jsokol** [comment]
The challenge that we run into is that we often don't control the environments where this gets installed on.  SimpleRisk is just an application that has the ability to use SAML for authentication.  What I've found is that we can still run it under the path you see (created automatically by Composer) as long as the configuration files are updated to point at the right place.  And since we use Composer, it makes upgrading from one version to the next far easier.

The metadata URL here should work fine:

https://dev.simplerisk.com/vendor/simplesamlphp/simplesamlphp/www/module.php/saml/sp/metadata.php/default-sp

When I hit it, I get a default-sp.xml file.  There is data in there that looks like metadata, but I'm no expert on that.  When I try to provide that URL to https://samltest.id/upload.php, it just sits there loading for forever.  However, if I upload the file instead, it seems to work.  Is that file missing data that you would have expected?

Thank you so much @tvdijen and @thijskh for your help on this!

**Comment by tvdijen** [comment]
Looks good to me

**Comment by jsokol** [comment]
Thanks @tvdijen!  And thank you all for the work you've done on SimpleSAMLphp!  As a fellow developer of open source software I know both the unrewarded time we take away from other things to work on something like this, as well as how much those who use it appreciate it.  You guys are awesome.
