### ISSUE TITLE
Custom error handler crashes when session is invalid

### ISSUE THREAD

**Issue by ghalse** [simplesamlphp/simplesamlphp#1809]
**Describe the bug**

The custom error handlers throw an exception when there is no valid session. This results in a fatal error, displaying a blank 500 error to end users.

**To Reproduce**

Throw any unhandled exception before the creation of a valid session.

For example, the exception thrown by unserialize() when trying to read an existing 1.19.x session will reliably trigger this.

**Expected behavior**

A helpful error message to be displayed to the user :-)

This probably requires a transient session to be created by the handler if there isn't a valid one.

**Screenshots or logs**

```
AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Typed property SimpleSAML\\Session::$trackid must not be accessed before initialization in /home/safire/simplesamlphp-2.0.3/src/SimpleSAML/Session.php:552
Stack trace:
#0 /home/safire/simplesamlphp-2.0.3/src/SimpleSAML/Session.php(399): SimpleSAML\\Session->getTrackID()
#1 /home/safire/simplesamlphp-2.0.3/src/SimpleSAML/Session.php(281): SimpleSAML\\Session::load()
#2 /home/safire/simplesamlphp-2.0.3/src/SimpleSAML/Error/Error.php(191): SimpleSAML\\Session::getSessionFromRequest()
#3 /home/safire/simplesamlphp-2.0.3/src/SimpleSAML/Error/Error.php(229): SimpleSAML\\Error\\Error->saveError()
#4 /home/safire/simplesamlphp-2.0.3/public/_include.php(32): SimpleSAML\\Error\\Error->show()
#5 [internal function]: SimpleSAML_exception_handler()
#6 {main}
thrown in /home/safire/simplesamlphp-2.0.3/src/SimpleSAML/Session.php on line 552`
```

**Comment by Eagle-Admin** [comment]
We're seeing the exact same behaviour in our enviroment.

`[02-Oct-2023 15:33:07 Europe/City] PHP Fatal error:  Uncaught Error: Typed property SimpleSAML\Session::$trackid must not be accessed before initialization in C:\inetpub\wwwroot\simplesamlphp_azuread\src\SimpleSAML\Session.php:552
Stack trace:
#0 C:\inetpub\wwwroot\simplesamlphp_azuread\src\SimpleSAML\Session.php(399): SimpleSAML\Session->getTrackID()
#1 C:\inetpub\wwwroot\simplesamlphp_azuread\src\SimpleSAML\Session.php(281): SimpleSAML\Session::load()
#2 C:\inetpub\wwwroot\simplesamlphp_azuread\src\SimpleSAML\Auth\Simple.php(52): SimpleSAML\Session::getSessionFromRequest()
#3 C:\inetpub\wwwroot\anmodning\login2.php(47): SimpleSAML\Auth\Simple->__construct()
#4 {main}
  thrown in C:\inetpub\wwwroot\simplesamlphp_azuread\src\SimpleSAML\Session.php on line 552`
