### ISSUE TITLE
Negotiate-module issue with LDAP-referrals

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#268]
I ran into an issue with the negotiate-module that I'd like to share. I have attached a piece of the log to this issue.

When doing a tcpdump, I could see that the LDAP-search was actually performing fine without any errors! So I'm a bit clueless on where the 'Operations error' is coming from.
Anyway, I found out that the problem was lying in the 'referrals' parameter.. It had to be turned off for the Active Directory I'm connecting to.

In /simplesamlphp-1.13.2/modules/negotiate/lib/Auth/Source/Negotiate.php, line 103, the LDAP-module is being called:
>> new SimpleSAML_Auth_LDAP($this->hostname, $this->enableTLS, $this->debugLDAP, $this->timeout);
This call lacks the arguments 'port' and 'referrals'.

I would like to suggest that these settings are made customizable in the authsources.php. They are for the LDAP-part of the config, but not for the Negotiate-part...

**Comment by tvdijen** [comment]
Will post pull-request soon

**Comment by tvdijen** [comment]
Log-file, because uploading a text-file tot Github is not possible at the moment:

>> Oct 07 08:20:52 simplesamlphp DEBUG [f93eca0527] Session: 'AD-KERBEROS' not valid because we are not authenticated.
>> Oct 07 08:20:52 simplesamlphp DEBUG [f93eca0527] Negotiate - SP disable flag not found
>> Oct 07 08:20:52 simplesamlphp DEBUG [f93eca0527] Negotiate - authenticate(): looking for Negotate
>> Oct 07 08:20:52 simplesamlphp DEBUG [f93eca0527] Negotiate - authenticate(): Negotate found
>> Oct 07 08:20:52 simplesamlphp DEBUG [f93eca0527] Library - LDAP __construct(): Setup LDAP with host='somewhere@example.nl', tls=false, debug=false, timeout=30, referrals=true
>> Oct 07 08:20:52 simplesamlphp INFO [f93eca0527] Negotiate - authenticate(): Snoa_TA_ssc98@EXAMPLE.NL authenticated.
>> Oct 07 08:20:52 simplesamlphp DEBUG [f93eca0527] Negotiate - authenticate(): Binding as system user 'CN=sa-gdi-idpldp-a,OU=ServiceAccounts,DC=example,DC=nl'
>> Oct 07 08:20:52 simplesamlphp DEBUG [f93eca0527] Library - LDAP bind(): Bind successful with DN 'CN=sa-gdi-idpldp-a,OU=ServiceAccounts,DC=example,DC=nl'
>> Oct 07 08:20:52 simplesamlphp DEBUG [f93eca0527] Library - LDAP search(): Searching base 'DC=example,DC=nl' for '(|(sAMAccountName=Snoa_TA_ssc98))'
>> Oct 07 08:20:52 simplesamlphp ERROR [f93eca0527] Library - LDAP search(): Failed search on base 'DC=example,DC=nl' for '(|(sAMAccountName=Snoa_TA_ssc98))'; cause: 'Operations error' (0x1)
>> Oct 07 08:20:52 simplesamlphp DEBUG [f93eca0527] Negotiate - ldap lookup failed: exception 'SimpleSAML_Error_AuthSource' with message 'AUTHSOURCEERROR('%AUTHSOURCE%' => '\'ldap\'', '%REASON%' => '$
>> Stack trace:
>> #0 /apps/simplesamlphp-1.13.2/lib/SimpleSAML/Auth/LDAP.php(216): SimpleSAML_Auth_LDAP->makeException('Library - LDAP ...')
>> #1 /apps/simplesamlphp-1.13.2/lib/SimpleSAML/Auth/LDAP.php(275): SimpleSAML_Auth_LDAP->search('DC=example,DC=nl', 'sAMAccountName', 'Snoa_TA_ssc98')
>> #2 /apps/simplesamlphp-1.13.2/modules/negotiate/lib/Auth/Source/Negotiate.php(270): SimpleSAML_Auth_LDAP->searchfordn('DC=example,DC=nl', 'sAMAccountName', 'Snoa_TA_ssc98')
>> #3 /apps/simplesamlphp-1.13.2/modules/negotiate/lib/Auth/Source/Negotiate.php(124): sspmod_negotiate_Auth_Source_Negotiate->lookupUserData('Snoa_TA_ssc98@A...')
>> #4 /apps/simplesamlphp-1.13.2/lib/SimpleSAML/Auth/Default.php(65): sspmod_negotiate_Auth_Source_Negotiate->authenticate(Array)
>> #5 /apps/simplesamlphp-1.13.2/lib/SimpleSAML/Auth/Simple.php(136): SimpleSAML_Auth_Default::initLogin('AD-KERBEROS', Array, NULL, Array)
>> #6 /apps/simplesamlphp-1.13.2/lib/SimpleSAML/IdP.php(328): SimpleSAML_Auth_Simple->login(Array)
>> #7 /apps/simplesamlphp-1.13.2/lib/SimpleSAML/IdP.php(390): SimpleSAML_IdP->authenticate(Array)
>> #8 /apps/simplesamlphp-1.13.2/modules/saml/lib/IdP/SAML2.php(389): SimpleSAML_IdP->handleAuthenticationRequest(Array)
>> #9 /apps/simplesamlphp-1.13.2/www/saml2/idp/SSOService.php(18): sspmod_saml_IdP_SAML2::receiveAuthnRequest(Object(SimpleSAML_IdP))
>> #10 {main}
>> Oct 07 08:20:52 simplesamlphp INFO [f93eca0527] Negotiate - authenticate(): Client failed Negotiate. Falling back

**Comment by tvdijen** [comment]
Will post pull-request soon

**Comment by tvdijen** [comment]
Pull-request has been merged. This issue can be closed now.
