### ISSUE TITLE
SimpleSAML configuration error : missing uid attribute

### ISSUE THREAD

**Issue by faustine1997** [simplesamlphp/simplesamlphp#882]
Hello,

I've been trying to configure SimpleSAML 1.15.4 in order to user the FileSender platform that I have installed on my computer.

When I launch Apache services, I can get to the authentification page of SimpleSAML. Then, I type the user name, the password on the SimpleSAML authentification page in order to access the filesender plateform. The user is authentificated successfully (I checked in /var/log/messages). But instead of showing me the FileSender plateform, I get an error message saying :

The application wasn't able to execute your request.
Missing uid attribute for Service Provider authentification.

Array ( [attribute] => uid )
 

It says that the attribute uid (user id) is missing in one of SimpleSAML's config files but I don't know which config file this message refers to.

Does anyone know in which config file this attribute should be ?

Here is what appears in the log :

[2018-07-04 07:58:30] [gui:warn] No translation found for auth_sp_attribute_uid_hint in fr-fr language
[2018-07-04 07:58:30] [gui:error] [AuthSPMissingAttributeException attributes uid:5b3c7016617d0] There have been problems finding an authentification attribute "Service Provider". These are the attributes available for authentification. Check if the spelling of the attribute is correct. May be the configuration is looking for the wrong attribute?

[2018-07-04 07:58:30] [gui:error] [AuthSPMissingAttributeException attributes uid:5b3c7016617d0] Configuration command associated 'uid_attribute'

[2018-07-04 07:58:30] [gui:error] [AuthSPMissingAttributeException attributes uid:5b3c7016617d0] Attribute required with the key 'eduPersonTargetedID'

[2018-07-04 07:58:30] [gui:error] [AuthSPMissingAttributeException attributes uid:5b3c7016617d0]     username = Array

[2018-07-04 07:58:30] [gui:error] [AuthSPMissingAttributeException attributes uid:5b3c7016617d0]     username = (

[2018-07-04 07:58:30] [gui:error] [AuthSPMissingAttributeException attributes uid:5b3c7016617d0]     username =     [0] => adminsimplesaml

[2018-07-04 07:58:30] [gui:error] [AuthSPMissingAttributeException attributes uid:5b3c7016617d0]     username = )

[2018-07-04 07:58:30] [gui:error] [AuthSPMissingAttributeException attributes uid:5b3c7016617d0]     username =

[2018-07-04 07:58:30] [gui:error] [AuthSPMissingAttributeException exception uid:5b3c7016617d0] auth_sp_missing_attribute

[2018-07-04 07:58:30] [gui:error] [AuthSPMissingAttributeException trace uid:5b3c7016617d0] #0 /opt/filesender/filesender/classes/auth/AuthSP.class.php(66): AuthSPSaml::attributes()

[2018-07-04 07:58:30] [gui:error] [AuthSPMissingAttributeException trace uid:5b3c7016617d0] #1 /opt/filesender/filesender/classes/auth/Auth.class.php(118): AuthSP::attributes()

[2018-07-04 07:58:30] [gui:error] [AuthSPMissingAttributeException trace uid:5b3c7016617d0] #2 /opt/filesender/filesender/classes/auth/Auth.class.php(214): Auth::user_protected()

[2018-07-04 07:58:30] [gui:error] [AuthSPMissingAttributeException trace uid:5b3c7016617d0] #3 /opt/filesender/filesender/classes/auth/Auth.class.php(257): Auth::user()

[2018-07-04 07:58:30] [gui:error] [AuthSPMissingAttributeException trace uid:5b3c7016617d0] #4 /opt/filesender/filesender/www/index.php(39): Auth::isAuthenticated()

[2018-07-04 07:58:30] [gui:error] [AuthSPMissingAttributeException trace uid:5b3c7016617d0] #5 {main}

[2018-07-04 07:58:30] [gui:error] [AuthSPMissingAttributeException details uid:5b3c7016617d0] attribute = "uid"

Faustine

**Comment by jaimeperez** [comment]
Hi @faustine1997!

This is an issue tracker, not a support forum. Please use the mailing list for support.

In any case, those errors appear to come from FileSender, so you should probably ask them for support.
